spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/secretsanta
    username: postgres
    password: mysecretpassword
    driver: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: update
        format_sql: true
    generate-ddl: true
